{1}{1}25.000
{486}{567}[Clocks ticking]
{2163}{2212}{Y:i}ANNOUNCER: October is inventory time.
{2214}{2300}{Y:i}So right now, Statler Toyota is making|the best deals of the year...
{2302}{2353}{Y:i}... on all 1985-model Toyotas.
{2355}{2397}{Y:i}You won't find a better car...
{2399}{2490}{Y:i}... at a better price with better service|anywhere in Hill Valley.
{2626}{2694}{Y:i}NEWSCASTER: The Senate is expected|to vote on this today.
{2696}{2800}{Y:i}In other news, officials at|the Pacific Nuclear research facility...
{2802}{2874}{Y:i}... have denied the rumor|that a case of missing plutonium...
{2876}{2945}{Y:i}... was in fact stolen|from their vault two weeks ago.
{2947}{3038}{Y:i}A Libyan terrorist group had claimed|responsibility for the alleged theft.
{3040}{3160}{Y:i}However, officials now attribute|the discrepancy to a simple clerical error.
{3162}{3250}{Y:i}The FBI, which is investigating the matter,|had no comment.
{3418}{3443}[Buzzer blares]
{4253}{4282}MARTY: Doc?
{4347}{4374}{Y:i}Doc?
{4402}{4452}{Y:i}Hello! Anybody home?
{4454}{4486}{Y:i}Einstein, come here, boy.
{4488}{4516}[Marty whistles]
{4518}{4564}MARTY: What's going on? God.
{4603}{4631}{Y:i}Jesus!
{4645}{4691}{Y:i}That is disgusting.
{4696}{4734}[Marty muttering]
{4810}{4850}[Clocks ticking]